url: next-gen-info.org
baseurl: /

# Site settings
title: Next Gen Info & Analytics
email: contact@next-gen-info.org
description: "Leveraging distrubted data points with Machine Learning and AI to provide elite data analytics for emerging industries."

# Team names, titles and social links
people:
- name: Craig Carsons
  pic: 1
  position: Cheif Innovation Officer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/craig-carsons-582b29174/
- name: Jin Lee
  pic: 2
  position: Senior Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jin-lee-048918190/



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/company/73919027


# Postal address (add as many lines as necessary)
address:
  - line: New York City, NY.

# Build settings
markdown: kramdown
